# Generated by Django 3.2.16 on 2024-05-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20240501_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='birthday_countdown',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Осталось до ДР'),
        ),
    ]
